src/dtu.blognet.Application.Web/Models/BlogViewModels/BlogViewModel.cs
using System.Collections;
using System.Collections.Generic;
using dtu.blognet.Application.Web.Models.PostViewModels;

namespace dtu.blognet.Application.Web.Models.BlogViewModels
{
    public class BlogViewModel
    {
        public string Title { get; set; }
        public int Id { get; set; }
        public string Description { get; set; }
        public bool IsOwner { get; set; }
        public ICollection<PostViewModel> Posts { get; set; }
    }
}

src/dtu.blognet.Application.Web/Controllers/BlogController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using dtu.blognet.Application.Web.Models.BlogViewModels;
using dtu.blognet.Core.Command.CommandHandlerFactories;
using dtu.blognet.Core.Command.Commands.BlogCommands;
using dtu.blognet.Core.Entities;
using dtu.blognet.Core.Query.Queries;
using dtu.blognet.Core.Query.Queries.BlogQueries;
using dtu.blognet.Core.Query.QueryFactories;
using dtu.blognet.Infrastructure.DataAccess.Migrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace dtu.blognet.Application.Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly IMapper _mapper;
        private readonly UserManager<Account> _userManager;

        public BlogController(IMapper mapper, UserManager<Account> userManager)
        {
            _mapper = mapper;
            _userManager = userManager;
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create([FromServices] BlogCommandHandlerFactory blogCommandHandlerFactory, AddBlogAsyncCommand command)
        {
            command.OwnerId = _userManager.GetUserId(User);
            var handler = blogCommandHandlerFactory.Build(command);
            var response = await handler.Execute();
            return RedirectToAction("Profile", "Account");
        }

        [HttpDelete]
        public async Task<IActionResult> Delete([FromServices] BlogCommandHandlerFactory blogCommandHandlerFactory, int id)
        {
            var command = new DeleteBlogAsyncCommand { Id = id };
            var handler = blogCommandHandlerFactory.Build(command);
            var response = await handler.Execute();
            return Ok();
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromServices] BlogQueryFactory blogFactory)
        {
            var query = new AllBlogsQueryAsync();
            var blogs = await blogFactory.Build(query).Get().ToList();
            var viewModel = _mapper.Map<BlogIndexViewModel>(blogs);
            return View(viewModel);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult View([FromServices] BlogQueryFactory blogQueryFactory, BlogFromIdQuery query)
        {
            var blog = blogQueryFactory.Build(query).Get();
            var viewModel = _mapper.Map<BlogViewModel>(blog);
            viewModel.IsOwner = blog.OwnerId == _userManager.GetUserId(User);
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Subscribe()
        {
            return Ok();
        }
        
    }
}

src/dtu.blognet.Application.Web/Controllers/PostController.cs
using System.Threading.Tasks;
using AutoMapper;
using dtu.blognet.Application.Web.Models.PostViewModels;
using dtu.blognet.Core.Command.CommandHandlerFactories;
using dtu.blognet.Core.Command.Commands.PostCommands;
using dtu.blognet.Core.Command.InputModels.PostInputModels;
using dtu.blognet.Core.Query.Queries.PostQueries;
using dtu.blognet.Core.Query.QueryFactories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace dtu.blognet.Application.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IMapper _mapper;

        public PostController(IMapper mapper)
        {
            _mapper = mapper;
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create([FromServices] PostCommandHandlerFactory postCommandHandlerFactory, PostInputModel model)
        {
            var command = new AddPostAsyncCommand {Model = model};
            var handler = postCommandHandlerFactory.Build(command);
            var response = await handler.Execute();
            return RedirectToAction("View", response.Response);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create(int blogId)
        {
            var viewModel = new PostViewModel {BlogId = blogId};
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult View([FromServices] PostQueryFactory postQueryFactory, PostFromIdQuery query)
        {
            var post = postQueryFactory.Build(query).Get();
            var viewModel = _mapper.Map<PostViewModel>(post);
            return View(viewModel);
        }
    }
}

src/dtu.blognet.Application.Web/Views/Blog/Create.cshtml
@model dtu.blognet.Application.Web.Models.BlogViewModels.BlogCreateViewModel
@{
    ViewData["Title"] = "Create Blog";
}

<form asp-action="Create">

    <h3 class="form-signin-heading" style="margin-top:0px;">Title</h3>
    <div class="form-group form-group-lg">
        <input type="text" class="form-control" style="max-width:100%;" aria-describedby="sizing-addon1" asp-for="Title">
    </div>

    <br />

    <h3 class="form-signin-heading" style="margin-top:0px;">Tags</h3>
    <div class="form-group form-group-lg">
        <input asp-for="Tags" type="text" class="form-control" style="max-width:100%;" aria-describedby="sizing-addon1">
    </div>

    <br/>

    <h3 class="form-signin-heading" style="margin-top:0px;">Description</h3>

    <textarea asp-for="Description" id="markdown-editor"></textarea>
    <input asp-for="Id" hidden="true"/>

    <input class="btn btn-lg btn-primary btn-block center-block" style="max-width:40%;" type="submit" value="Create blog" />

</form>

@section Scripts
{
    <script>
        var simplemde = new SimpleMDE({ element: document.getElementById("markdown-editor") });
    </script>
}

src/dtu.blognet.Application.Web/Views/Blog/Index.cshtml
@model dtu.blognet.Application.Web.Models.BlogViewModels.BlogIndexViewModel
@{
    ViewData["Title"] = "Blogs";
}

<div class="row">
    <div class="col-md-8">
        <div class="btn-group" role="group" aria-label="Large button group" style="width:100%;">
            <button type="button" class="btn btn-default" style="width:33%;">All</button>
            <button type="button" class="btn btn-default" style="width:33%;">Subscribed</button>
            <button type="button" class="btn btn-default" style="width:33%;">Newly updated</button>
        </div>
    </div>
    <div class="col-md-4">
        <select class="js-example-basic-multiple" multiple id="e1" style="width:100%;">
            <option value="AL">Alabama</option>
            <option value="WY">Wyoming</option>
            <option value="WY">Wyoming</option>
            <option value="WY">Wyoming</option>
            <option value="WY">Wyoming</option>
            <option value="WY">Wyoming</option>
            <option value="WY">Wyoming</option>
        </select>
    </div>
</div>

<br />

<div class="list-group">

    @foreach (var blog in Model.Blogs)
    {
        <a class="list-group-item" asp-action="View" asp-route-id="@blog.Id">
            <h4 class="list-group-item-heading">@blog.Title</h4>
            <p class="list-group-item-text">Tags: 
                @foreach (var tag in blog.Tags)
                  {
                      <span>#@tag </span>    
                  }
                </p>
            <br/>
            <p class="list-group-item-text">@blog.Description</p>
        </a>
    }

</div>

@section Scripts
    {

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

    <script type="text/javascript">
        $("#e1").select2({
            placeholder: "Search by tags"
        });
    </script>

}

src/dtu.blognet.Application.Web/Views/Blog/View.cshtml
@model dtu.blognet.Application.Web.Models.BlogViewModels.BlogViewModel

@{
    ViewBag.Title = $"Blog - {Model.Title}";
}


<div id="app">
    <div class="jumbotron">

        <div class="row">
            <div class="col-xs-11">
                <h2 class="text-center">@Model.Title</h2>
            </div>
            <div class="col-xs-1">
                <a v-if="btnShow" v-on:click="subscripe" class="btn btn-primary">Subscribe</a>
                <a v-else v-on:click="unSubscripe" class="btn btn-danger">Unsubscribe</a>
            </div>
        </div>
    
        <p class="text-center">
            @foreach (var tag in Model.Tags)
            {
                <span>@tag, </span>    
            }
        </p>
        <br />
        <div id="md-description"></div>

        <div class="row">
            <div class="col-sm-6">
                <a class="btn btn-success btn-lg center-block" style="width:50%;" asp-controller="Blog" asp-action="Create">
                    <i class="glyphicon glyphicon-cog"></i>
                </a>
            </div>

            <div class="col-sm-6">
                <a class="btn btn-danger btn-lg center-block" style="width:50%;" asp-controller="Blog" asp-action="Create">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </div>
        </div>

    </div>
</div>


<div class="row">
    <div class="col-md-8">
        <h2>Posts</h2>
    </div>
    <div class="col-md-4">

        @if (Model.IsOwner)
        {
            <a class="btn btn-primary center-block" asp-controller="Post" asp-action="Create" asp-route-blogId="@Model.Id">New post</a>
        }

    </div>
</div>


<div class="list-group">

    @foreach (var post in Model.Posts)
    {

        <a class="list-group-item" asp-controller="Post" asp-action="View" asp-route-id="@post.Id">
            <h4 class="list-group-item-heading">@post.Title</h4>
            <p class="list-group-item-text">Tags: Sport, Music, Fun</p>
            <br />
            <div id="md-description"></div>
        </a>


    }

</div>

@section Scripts
    {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js" integrity="sha256-mJAzKDq6kSoKqZKnA6UNLtPaIj8zT2mFnWu/GSouhgQ=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/vue"></script>
    <script>
        document.getElementById('md-description').innerHTML =
            marked('@Model.Description');

        const url = `/api/subscription/${@Model.Id}`;
        const app = new Vue({
            el: '#app',
            data: {
                btnShow : true

            },
            mounted() {
                this.isSubscriped();
            },
            methods: {
                isSubscriped: function() {
                    axios.get(url)
                        .then(response => {
                            this.btnShow = !response.data.isSubscriped;
                        });
                },
                subscripe: function() {
                    var self = this;
                    axios.post('/api/subscription',
                            {
                                blogId: @Model.Id
                            })
                        .then(function(response) {
                            console.log(response);
                            self.isSubscriped();
                        })
                        .catch(function(error) {
                            console.log(error);
                        });
                },
                unSubscripe: function() {
                    var self = this;
                    axios.delete(`/api/subscription?blogId=${@Model.Id}`)
                        .then(function(response) {
                            console.log(response);
                            self.isSubscriped();
                        })
                        .catch(function(error) {
                            console.log(error);
                        });
                }
            }
        });
    </script>
}